### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by szepeviktor** [eusonlito/php-changes-reference#1]
Please consider adding horizontal scrolling.

**Comment by eusonlito** [comment]
Thanks for reporting. We are working in a different layout to compare same changes types (like `new-features`) with all versions together.

**Comment by eusonlito** [comment]
Hello @szepeviktor, we have published new version and we are noew working with styles https://eusonlito.github.io/php-changes-cheatsheet/

**Comment by szepeviktor** [comment]
Thank you.
This design provides a much better UX.
