### ISSUE TITLE
libcurl

### ISSUE THREAD

**Issue by serkanhamarat** [eusonlito/php-changes-reference#9]
I think CURLOPT_SAFE_UPLOAD is no longer supported from 7.0 and I cannot find it in this project. Code  "curl_setopt($curl_pointer, CURLOPT_SAFE_UPLOAD, false);" generates: "PHP Fatal error:  Uncaught ValueError: curl_setopt(): Disabling safe uploads is no longer supported in ..."

**Comment by eusonlito** [comment]
The `CURLOPT_SAFE_UPLOAD` behaviour can not be changed.

https://www.php.net/manual/en/function.curl-setopt.php

> Always true, what disables support for the @ prefix for uploading files in CURLOPT_POSTFIELDS, which means that values starting with @ can be safely passed as fields. CURLFile may be used for uploads instead.

Some other translations include:

> Added in PHP 5.5.0 with false as default. PHP 5.6.0 used to set this default to true. PHP 7 removes this option; the CURLFile interface must be used for file uploads.
